apiVersion: v1
kind: Secret
metadata:
  name: {{ include "simple-rest.fullname" . }}-pgs
  labels:
{{ include "simple-rest.labels" . | indent 4 }}
data:
  password: {{ .Values.app.PostgresPassword | b64enc | quote }}